name: Upload Repository to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@v1.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          folder: '1BjfHmFuqDoRZgoHzH-Mm_GyolWTL8v9l'
          target: '.'
