name: Upload Docs to Google Drive
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Upload Docs Folder to Google Drive
        uses: Jodebu/upload-to-drive@v1.0.0
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder: '1BjfHmFuqDoRZgoHzH-Mm_GyolWTL8v9l'
          target: 'docs'